---
# tasks file for install_httpd

- name: Print Linux family
  debug: var=ansible_os_family

- block:
    - name: Install Apache
      yum:
        name: httpd
        state: latest

    - name: index.html from template
      template: src=index.j2 dest={{ destination_path }}/index.html
      notify:
        - Restart httpd

    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Enable port
      firewalld:
        port: "{{ tcp_port }}/tcp"
        permanent: yes
        state: enabled
      notify:
        - Restart firewall
  when: ansible_os_family == "RedHat"
