---
# tasks file for install_ftp

- name: Print Linux family
  debug: var=ansible_os_family

- block:
    - name: Install FTP
      yum:
        name: vsftpd
        state: latest

    - name: Enable FTP
      service:
        name: vsftpd
        state: started
        enabled: yes


    - name: Enable port
      firewalld:
        port: "{{ tcp_port }}/tcp"
        permanent: yes
        state: enabled
      notify:
        - Restart firewall


    - name: Install package for SELinux
      ansible.builtin.package:
        name: "python3-libsemanage"
        state: present

    - name: Set SElinux on
      seboolean:
        name: "{{ item }}"
        state: true
        persistent: yes
      with_items:
        - "{{ se_anon_write }}"
        - "{{ se_full_access }}"

    - name: Print SELinux context
      command: getsebool {{ se_anon_write }} {{ se_full_access }}
      register: selinux_msg

    - debug: msg="{{ selinux_msg.stdout }}"


    - name: Create a directory
      file:
        path: "{{ ftp_path }}/upload"
        state: directory
        mode: "0755"
        owner: ftp

    - name: Create a test file
      copy:
        content: "Hello from FTP!"
        dest: "{{ ftp_path }}/readme.txt"


    - name: vsftpd.conf from template
      template: src=vsftpd.j2 dest={{ destination_path }}/vsftpd.conf
      notify:
        - Restart ftp
 
  when: ansible_os_family == "RedHat"
